"""Step 01: build the candidate inventory (02-candidates.toml).

Enumerates every candidate in the fixed sampling frame declared in
01-sampling.toml, inspects each from its source bytes only, applies the
predeclared eligibility and exclusion rules, and writes the complete
screening record, including every excluded candidate and its reasons.

Source-only. No converter is run and the evaluator's comparison logic is
never called. Corpus selection is a separate step that reads this record.

Before screening, this step verifies:
- the Freeze 01 record matches the current bytes of every frozen artifact
  (the frozen source adapter is used during screening);
- the sampling specification loads and contains no placeholders;
- every validation exclusion derivable from validation/ and the fixtures
  is declared in the sampling specification;
- each clone is the declared repository and contains its pinned revision.

The output is write-once and byte-identical on rerun with identical inputs.

Usage (relative paths resolve against the repository root):

    uv run python -m preservation_test.generalization.01_build_candidates

    uv run python -m preservation_test.generalization.01_build_candidates `
        --config generalization/01-sampling.toml `
        --clone-root ../generalization-clones `
        --out generalization/02-candidates.toml

    # Print the validation exclusions derived from this repository:
    uv run python -m preservation_test.generalization.01_build_candidates `
        --print-derived-exclusions

Clones live at <clone-root>/<repository-name>, for example
../generalization-clones/bom-examples, and must contain the pinned revision.
"""

import argparse
from collections import Counter
from pathlib import Path
import sys

from preservation_test.generalization.models.candidate import Candidate
from preservation_test.generalization.utils.freeze_integrity import (
    FREEZE_01_RECORD,
    FreezeIntegrityError,
    verify_freeze,
)
from preservation_test.generalization.utils.git_blobs import GitError
from preservation_test.generalization.utils.sampling_config import (
    SamplingConfigError,
    load_sampling_config,
)
from preservation_test.generalization.utils.screening import (
    candidate_row,
    provenance_fields,
    relative_to_root,
    screen,
    screening_code_hashes,
)
from preservation_test.generalization.utils.toml_writer import (
    render_document,
    write_new_file,
)
from preservation_test.generalization.utils.validation_exclusions import (
    derive_validation_exclusions,
    missing_exclusions,
    render_exclusion_entries,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
THIS_STEP = Path(__file__).resolve()

DEFAULT_CONFIG = Path("generalization/01-sampling.toml")
DEFAULT_CLONE_ROOT = Path("../generalization-clones")
DEFAULT_OUT = Path("generalization/02-candidates.toml")

EXIT_OK = 0
EXIT_PRECONDITION = 2


def _resolve(path: Path) -> Path:
    return path if path.is_absolute() else REPOSITORY_ROOT / path


def _fail(message: str) -> int:
    sys.stderr.write(f"CANDIDATES NOT BUILT.\n{message}\n")
    return EXIT_PRECONDITION


def _summary(candidates: list[Candidate]) -> str:
    eligible = [item for item in candidates if item.screening.eligible]
    reasons = Counter(
        reason for item in candidates for reason in item.screening.exclusion_reasons
    )
    lines = [
        f"screened: {len(candidates)}",
        f"eligible: {len(eligible)}",
        *(f"excluded [{reason}]: {count}" for reason, count in sorted(reasons.items())),
    ]
    return "\n".join(lines)


def build_candidates(config_path: Path, clone_root: Path, out: Path) -> int:
    """Run step 01 and write the candidate inventory."""
    if out.exists():
        return _fail(f"refusing to overwrite {out}")

    try:
        freeze_record_sha256 = verify_freeze(REPOSITORY_ROOT)
    except FreezeIntegrityError as error:
        return _fail(str(error))

    try:
        config = load_sampling_config(config_path)
    except (OSError, SamplingConfigError) as error:
        return _fail(f"sampling specification: {error}")

    missing = missing_exclusions(config, derive_validation_exclusions(REPOSITORY_ROOT))
    if missing:
        return _fail(
            "sampling specification is missing derived validation exclusions:\n\n"
            + render_exclusion_entries(missing)
        )

    try:
        candidates = screen(config, clone_root)
    except GitError as error:
        return _fail(f"sampling frame: {error}")

    text = render_document(
        header=[
            "02-candidates.toml",
            "Generated by preservation_test.generalization.p01_build_candidates.",
            "Source-only screening record of every candidate in the sampling frame.",
            "Do not edit by hand.",
        ],
        tables={
            "screening": {
                **provenance_fields(config, REPOSITORY_ROOT),
                "freeze_01_record": FREEZE_01_RECORD.as_posix(),
                "freeze_01_record_sha256": freeze_record_sha256,
                "screened": len(candidates),
                "eligible": sum(1 for item in candidates if item.screening.eligible),
            },
            "screening_code_sha256": screening_code_hashes(
                REPOSITORY_ROOT, extra=(THIS_STEP,)
            ),
        },
        arrays={"candidate": [candidate_row(item) for item in candidates]},
    )
    write_new_file(out, text)

    print(f"wrote {relative_to_root(out, REPOSITORY_ROOT)}")
    print(_summary(candidates))
    return EXIT_OK


def main(argv: list[str] | None = None) -> int:
    """Parse arguments and run step 01."""
    parser = argparse.ArgumentParser(
        description="Step 01: build the source-only candidate inventory."
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--clone-root", type=Path, default=DEFAULT_CLONE_ROOT)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--print-derived-exclusions",
        action="store_true",
        help="print [[validation_exclusion]] entries derived from this repository",
    )
    args = parser.parse_args(argv)

    if args.print_derived_exclusions:
        sys.stdout.write(
            render_exclusion_entries(derive_validation_exclusions(REPOSITORY_ROOT))
        )
        return EXIT_OK

    return build_candidates(
        config_path=_resolve(args.config),
        clone_root=_resolve(args.clone_root),
        out=_resolve(args.out),
    )


if __name__ == "__main__":
    raise SystemExit(main())
